apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
    [options]
    db_host = postgres
    db_user = odoo
    db_port = 5432
    db_password = odoo
    addons_path = /mnt/extra-addons
