apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer  #  LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432  # Set target port to match the container port
  selector:
    app: postgres
